class { 'appdynamics::agent':
  agent_types                           =>  [
                                        'db',
                                        'jboss',
                                        'machine',
                                        'php',
                                        'tomcat'
                                        ],
  package_ensure                        =>  'installed',

  db_agent_base                         =>  '/string',
  db_agent_home                         =>  'string1',
  db_group                              =>  'string',
  db_user                               =>  'string',
  db_app                                =>  'string',
  db_tier                               =>  'string',
  db_controller_host                    =>  'string',
  db_controller_port                    =>  80,
  db_controller_ssl_enabled             =>  true,
  db_enable_orchestration               =>  true,
  db_account_name                       =>  'string',
  db_account_access_key                 =>  'string',
  db_force_agent_registration           =>  true,
  db_node_name                          =>  'string',
  db_agent_options                      =>  'string',
  db_application_home                   =>  '/string',

  jboss_agent_base                      =>  '/string',
  jboss_agent_home                      =>  'string2',
  jboss_group                           =>  'string',
  jboss_user                            =>  'string',
  jboss_app                             =>  'string',
  jboss_tier                            =>  'string',
  jboss_controller_host                 =>  'string',
  jboss_controller_port                 =>  80,
  jboss_controller_ssl_enabled          =>  true,
  jboss_enable_orchestration            =>  true,
  jboss_account_name                    =>  'string',
  jboss_account_access_key              =>  'string',
  jboss_force_agent_registration        =>  true,
  jboss_node_name                       =>  'string',
  jboss_agent_options                   =>  'string',
  jboss_application_home                =>  '/string',

  machine_agent_base                    =>  '/string',
  machine_agent_home                    =>  'string3',
  machine_group                         =>  'string',
  machine_user                          =>  'string',
  machine_app                           =>  'string',
  machine_tier                          =>  'string',
  machine_controller_host               =>  'string',
  machine_controller_port               =>  80,
  machine_controller_ssl_enabled        =>  true,
  machine_enable_orchestration          =>  true,
  machine_account_name                  =>  'string',
  machine_account_access_key            =>  'string',
  machine_force_agent_registration      =>  true,
  machine_node_name                     =>  'string',
  machine_agent_options                 =>  'string',
  machine_application_home              =>  '/string',

  php_agent_base                        =>  '/string',
  php_agent_home                        =>  'string4',
  php_group                             =>  'string',
  php_user                              =>  'string',
  php_app                               =>  'string',
  php_tier                              =>  'string',
  php_controller_host                   =>  'string',
  php_controller_port                   =>  80,
  php_controller_ssl_enabled            =>  true,
  php_enable_orchestration              =>  true,
  php_account_name                      =>  'string',
  php_account_access_key                =>  'string',
  php_force_agent_registration          =>  true,
  php_node_name                         =>  'string',
  php_agent_options                     =>  'string',
  php_application_home                  =>  '/string',

  tomcat_agent_base                     =>  '/string',
  tomcat_agent_home                     =>  'string5',
  tomcat_group                          =>  'string',
  tomcat_user                           =>  'string',
  tomcat_app                            =>  'string',
  tomcat_tier                           =>  'string',
  tomcat_controller_host                =>  'string',
  tomcat_controller_port                =>  80,
  tomcat_controller_ssl_enabled         =>  true,
  tomcat_enable_orchestration           =>  true,
  tomcat_account_name                   =>  'string',
  tomcat_account_access_key             =>  'string',
  tomcat_force_agent_registration       =>  true,
  tomcat_node_name                      =>  'string',
  tomcat_agent_options                  =>  'string',
  tomcat_application_home               =>  '/string',
}